/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import static Interfaz.Aspirante.TxtCcasp;
import Logica.LTutorias;
import java.awt.BorderLayout;
import java.io.File;
import javax.swing.JOptionPane;


public class AEstudiante extends javax.swing.JFrame {
 public LTutorias ltu = new LTutorias();
    private String usuarioasp=null,tipo ="Estudiante",nombre=null,contrasp=null,cc=null,tel=null,edad=null;
    private long numt=0,ccasp=0,telasp=0,edadasp=0,cartera=0,codexamen=0,puntaje=0;
    
    /**
     * Creates new form Aspirante
     */
    public AEstudiante() {
        initComponents();
        Fondo2 f= new Fondo2();
        this.add(f, BorderLayout.CENTER);
        this.pack();
         String s5 = "Personas.csv";
            File f5 = new File(s5);
            if(f5.exists()){

                ltu.cargararchivousu();
            }
            String sFichero = "Estudiantes.csv";
            File fichero = new File(sFichero);
            if(fichero.exists()){

           ltu.cargararchivoest();}
            
             String s2 = "Materias Estudiantes.csv";
            File fichero2 = new File(s2);
            if(fichero2.exists()){

           ltu.cargararchivomae();}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel23 = new javax.swing.JPanel();
        ComboUbiasp = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        TxtCcasp = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        TxtNombreasp = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        Txtdirasp = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        Txtelasp = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        TxtCorreoasp = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        ComboMateriasest = new javax.swing.JComboBox();
        BtnGuardarHV2 = new javax.swing.JButton();
        TxtEdadasp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        BtnGuardarHV3 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        TxtUsuasp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        recontra = new javax.swing.JPasswordField();
        verificarcontra = new javax.swing.JButton();
        BtnGuardarHV = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        BtnIngresar3 = new javax.swing.JButton();
        BtnGuardarHV1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(51, 204, 0));
        setResizable(false);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ComboUbiasp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Armenia (Quindio)", "Barranquilla (Atlantico)", "Bogota D.C", "Bucaramanga (Santander)", "Cartagena (Bolivar)", "Cucuta (Norte de Santander)", "Pereira (Risaralda)", "Ibague (Tolima)", "Manizales (Caldas)", "Neiva (Huila)", "Santa Marta (Magdalena)", "Tunja (Boyaca)", "Villavicencio (Meta)" }));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Materias a ver:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Número Documento:");

        TxtCcasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCcaspActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Nombres completos:");

        TxtNombreasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreaspActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Dirección:");

        Txtdirasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtdiraspActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Teléfono:");

        Txtelasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtelaspActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Correo:");

        TxtCorreoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreoaspActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Ubicación:");

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Edad:");

        ComboMateriasest.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Calculo Diferencial", "Calculo Integral", "Calculo Multivariado", "Fisica Mecanica", "Electromagnetica", "Programacion Basica", "Programacion Orientada a Objetos" }));

        BtnGuardarHV2.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnGuardarHV2.setText("Agregar ");
        BtnGuardarHV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHV2ActionPerformed(evt);
            }
        });

        TxtEdadasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEdadaspActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(39, 39, 39));
        jLabel30.setText("Disponibilidad horaria:");

        BtnGuardarHV3.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnGuardarHV3.setText("Agregar ");
        BtnGuardarHV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHV3ActionPerformed(evt);
            }
        });

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Usuario:");

        TxtUsuasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuaspActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Contraseña:");

        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Confirmar contraseña:");

        verificarcontra.setBackground(new java.awt.Color(204, 204, 255));
        verificarcontra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verificarcontra.setText("Verificar ");
        verificarcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarcontraActionPerformed(evt);
            }
        });

        BtnGuardarHV.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        BtnGuardarHV.setText("Guardar ");
        BtnGuardarHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHVActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\KARIN\\Downloads\\kkk\\marcel.jpg")); // NOI18N

        jLabel3.setIcon(new javax.swing.ImageIcon("C:\\Users\\KARIN\\Downloads\\kkk\\globo.jpg")); // NOI18N

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(BtnGuardarHV2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel42)
                                .addGap(56, 56, 56)
                                .addComponent(ComboMateriasest, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(135, 135, 135))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                .addComponent(BtnGuardarHV3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(169, 169, 169))))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(BtnGuardarHV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel23Layout.createSequentialGroup()
                                    .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(54, 54, 54)
                                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtCorreoasp)
                                        .addComponent(Txtelasp)
                                        .addComponent(Txtdirasp)
                                        .addComponent(TxtEdadasp, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(ComboUbiasp, 0, 293, Short.MAX_VALUE))))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TxtNombreasp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TxtCcasp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(49, 49, 49)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(50, 50, 50)
                                        .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(recontra, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(verificarcontra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 857, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 25, Short.MAX_VALUE))))
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 535, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel45))
                                .addGap(23, 23, 23)
                                .addComponent(TxtUsuasp, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(TxtCcasp, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(contra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtNombreasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(recontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtUsuasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(verificarcontra)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel42)
                    .addComponent(ComboMateriasest, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel30))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnGuardarHV3)
                    .addComponent(BtnGuardarHV2))
                .addGap(5, 5, 5)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(Txtelasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel46)
                                    .addComponent(Txtdirasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel47))))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel51)
                                    .addComponent(TxtEdadasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel48)
                                    .addComponent(TxtCorreoasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel49)
                                    .addComponent(ComboUbiasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGap(29, 29, 29)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)
                        .addComponent(BtnGuardarHV))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        BtnIngresar3.setBackground(new java.awt.Color(255, 255, 255));
        BtnIngresar3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        BtnIngresar3.setText("Salir");
        BtnIngresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresar3ActionPerformed(evt);
            }
        });

        BtnGuardarHV1.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        BtnGuardarHV1.setText("Volver a Inicio");
        BtnGuardarHV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(184, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGuardarHV1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnIngresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnIngresar3)
                    .addComponent(BtnGuardarHV1))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresar3ActionPerformed

        //cierro mi programa
        this.show(false);
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIngresar3ActionPerformed

    private void verificarcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarcontraActionPerformed
try {
            String sFichero = "Personas.csv";
            File fichero = new File(sFichero);
            if(fichero.exists()){

                }else{
                ltu.crearcvsusu();
            }
          cc=TxtCcasp.getText().toString();
                ccasp= Long.parseLong(cc);
            usuarioasp=TxtUsuasp.getText().toString();
      //  System.out.println("usuario"+usuarioasp);
        nombre=TxtNombreasp.getText().toString();
      //  System.out.println("nombre"+nombre);
       contrasp= contra.getText().toString();
     //   System.out.println("contraseña"+contrasp);
        
            for (int i = 0; i < ltu.getPer().size(); i++) {
                
                if((usuarioasp.equals(ltu.getPer().get(i).getPersona()))&&(contrasp.equals(ltu.getPer().get(i).getContraseña()))){
                   JOptionPane.showMessageDialog(null, "Error, el usuario y la contraseña ya existen",null,JOptionPane.ERROR_MESSAGE);   
        break;
                    
                }
            }
        if(contra.getText().toString().equals(recontra.getText().toString())){
            
         ltu.persona(usuarioasp, tipo, nombre, contrasp);
                    JOptionPane.showMessageDialog(null, "Las contraseñas son iguales",null,JOptionPane.INFORMATION_MESSAGE);   

        }else{
         JOptionPane.showMessageDialog(null, "Error, las contraseñas no coinciden, puede continuar",null,JOptionPane.ERROR_MESSAGE);   
        }
        
      
        } catch (Exception e) {
        JOptionPane.showMessageDialog(null, "Error",null,JOptionPane.ERROR_MESSAGE);

        } 
                // TODO add your handling code here:
        
    }//GEN-LAST:event_verificarcontraActionPerformed

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void TxtUsuaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuaspActionPerformed

    private void BtnGuardarHV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHV3ActionPerformed

                System.out.println("ccasp"+ccasp);
                HorarioEstudiante ht=new HorarioEstudiante();
ht.setScc(ccasp);
ht.setVisible(true);       // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarHV3ActionPerformed

    private void TxtEdadaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEdadaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEdadaspActionPerformed

    private void BtnGuardarHV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHV2ActionPerformed

        try {
            if(ComboMateriasest.getSelectedItem().toString().equals("...")){
                JOptionPane.showMessageDialog(null, "Ingrese una materia",null,JOptionPane.ERROR_MESSAGE);
            }
            ltu.crearmae(ccasp, ComboMateriasest.getSelectedItem().toString());
            ltu.crearcvsmae();
                 JOptionPane.showMessageDialog(null, "Materia agregada",null,JOptionPane.INFORMATION_MESSAGE);   
        } catch (Exception e) {
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarHV2ActionPerformed

    private void TxtCorreoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreoaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCorreoaspActionPerformed

    private void TxtelaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtelaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtelaspActionPerformed

    private void TxtdiraspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtdiraspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtdiraspActionPerformed

    private void TxtNombreaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreaspActionPerformed

    private void TxtCcaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCcaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCcaspActionPerformed

    private void BtnGuardarHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHVActionPerformed
try {
            String sFichero = "Estudiante.csv";
            File fichero = new File(sFichero);
            if(fichero.exists()){
}else{
                ltu.crearcvsest();
            }
              if((usuarioasp!=null)&&(nombre!=null)&&(contrasp!=null)&&(tipo!=null)){
             

                cc=TxtCcasp.getText().toString();
                ccasp= Long.parseLong(cc);
              
                tel=Txtelasp.getText().toString();
                telasp=Long.parseLong(tel);
                edad=TxtEdadasp.getText().toString();
            
               edadasp=Long.parseLong(edad);System.out.println("nombre"+nombre);
                System.out.println("tipo"+tipo);
//nomest, direst,correst,ubiest,ccesti,telesti, edadesti, usuario, tipo, nombreusuario, contraseña
                ltu.estudiante(TxtNombreasp.getText().toString(), Txtdirasp.getText().toString(),
                        TxtCorreoasp.getText().toString(),ComboUbiasp.getSelectedItem().toString(),
                        ccasp,telasp,edadasp,usuarioasp, tipo, nombre, contrasp,cartera);

                System.out.println("ahi vamos2");

                for (int j = 0; j < ltu.getEst().size(); j++) {
                    System.out.println("array edad"+ltu.getEst().get(j).getEdadest());

                }

ltu.crearcvsest();
ltu.crearcvsusu();

                     JOptionPane.showMessageDialog(null, "Datos guardados exitosamente",null,JOptionPane.INFORMATION_MESSAGE);   

                System.out.println("lleno");

                System.out.println("tamaño"+ltu.getEst().size());

              }else{
      JOptionPane.showMessageDialog(null, "Por favor ingrese su usuario y contraseña para crear su perfil", null,JOptionPane.ERROR_MESSAGE);

              }

        }catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error",null,JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarHVActionPerformed

    private void BtnGuardarHV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHV1ActionPerformed
new Inicio().setVisible(true);
        this.show(false);
// TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarHV1ActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarHV;
    private javax.swing.JButton BtnGuardarHV1;
    private javax.swing.JButton BtnGuardarHV2;
    private javax.swing.JButton BtnGuardarHV3;
    private javax.swing.JButton BtnIngresar3;
    private javax.swing.JComboBox ComboMateriasest;
    private javax.swing.JComboBox ComboUbiasp;
    private javax.swing.JTextField TxtCcasp;
    private javax.swing.JTextField TxtCorreoasp;
    private javax.swing.JTextField TxtEdadasp;
    private javax.swing.JTextField TxtNombreasp;
    private javax.swing.JTextField TxtUsuasp;
    private javax.swing.JTextField Txtdirasp;
    private javax.swing.JTextField Txtelasp;
    private javax.swing.JPasswordField contra;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JPasswordField recontra;
    private javax.swing.JButton verificarcontra;
    // End of variables declaration//GEN-END:variables
}
