/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Datos.Horariotutor;
import Logica.LTutorias;
import java.awt.BorderLayout;
import java.awt.List;
import java.io.File;
import java.util.ArrayList;
import java.util.LinkedList;
import javax.swing.JList;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;


public class Aspirante extends javax.swing.JFrame {
 public LTutorias ltu = new LTutorias();
    private String usuarioasp=null,tipo ="Tutor",nombre=null,contrasp=null,cc="",tel=null,edad=null,estasp=null;
    private long numt=0,ccasp=0,telasp=0,edadasp=0,cartera=0,codexamen=0,puntaje=0;
    LinkedList lunes = new LinkedList();
    LinkedList martes = new LinkedList();
    LinkedList miercoles = new LinkedList();
    LinkedList jueves = new LinkedList();
    LinkedList viernes= new LinkedList();
    ArrayList horario=new ArrayList();
    
    /**
     * Creates new form Aspirante
     */
    public Aspirante() {
        initComponents();
        Fondo2 f= new Fondo2();
        this.add(f, BorderLayout.CENTER);
        this.pack();
         String s5 = "Personas.csv";
            File f5 = new File(s5);
            if(f5.exists()){

                ltu.cargararchivousu();
            }
            String sFichero = "Tutores.csv";
            File fichero = new File(sFichero);
            if(fichero.exists()){

           ltu.cargararchivotut();}
            
            String s1 = "Calificaciones.csv";
            File fichero1 = new File(s1);
            if(fichero1.exists()){

           ltu.cargararchivoca();}
            
            String s2 = "Materias.csv";
            File fichero2 = new File(s2);
            if(fichero2.exists()){

           ltu.cargararchivoma();}
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel23 = new javax.swing.JPanel();
        ComboUbiasp = new javax.swing.JComboBox();
        jLabel42 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        TxtCcasp = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        TxtNombreasp = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        Txtdirasp = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        Txtelasp = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        TxtCorreoasp = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        ComboMateriasasp = new javax.swing.JComboBox();
        jLabel22 = new javax.swing.JLabel();
        ComboProfesión = new javax.swing.JComboBox();
        jLabel36 = new javax.swing.JLabel();
        codexam = new javax.swing.JTextField();
        Verificarexam = new javax.swing.JButton();
        jLabel43 = new javax.swing.JLabel();
        puntajeexam = new javax.swing.JTextField();
        jLabel58 = new javax.swing.JLabel();
        fechacitacio = new javax.swing.JTextField();
        BtnGuardarHV2 = new javax.swing.JButton();
        TxtEdadasp = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        BtnGuardarHV3 = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel40 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        TxtUsuasp = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        contra = new javax.swing.JPasswordField();
        jLabel39 = new javax.swing.JLabel();
        recontra = new javax.swing.JPasswordField();
        verificarcontra = new javax.swing.JButton();
        jLabel37 = new javax.swing.JLabel();
        Combolugarexam = new javax.swing.JComboBox();
        BtnGuardarHV = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        BtnIngresar3 = new javax.swing.JButton();
        BtnGuardarHV1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel23.setBackground(new java.awt.Color(255, 255, 255));
        jPanel23.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        ComboUbiasp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Armenia (Quindio)", "Barranquilla (Atlantico)", "Bogota D.C", "Bucaramanga (Santander)", "Cartagena (Bolivar)", "Cucuta (Norte de Santander)", "Pereira (Risaralda)", "Ibague (Tolima)", "Manizales (Caldas)", "Neiva (Huila)", "Santa Marta (Magdalena)", "Tunja (Boyaca)", "Villavicencio (Meta)" }));

        jLabel42.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel42.setText("Materias a dictar:");

        jLabel44.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel44.setText("Cédula:");

        TxtCcasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCcaspActionPerformed(evt);
            }
        });

        jLabel45.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel45.setText("Nombres completos:");

        TxtNombreasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNombreaspActionPerformed(evt);
            }
        });

        jLabel46.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel46.setText("Dirección:");

        Txtdirasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtdiraspActionPerformed(evt);
            }
        });

        jLabel47.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel47.setText("Teléfono:");

        Txtelasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtelaspActionPerformed(evt);
            }
        });

        jLabel48.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel48.setText("Correo:");

        TxtCorreoasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtCorreoaspActionPerformed(evt);
            }
        });

        jLabel49.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel49.setText("Ubicación:");

        jLabel26.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(39, 39, 39));
        jLabel26.setText("Escribe los siguientes datos para verificar los resultados de tu prueba de aptitud:");

        jLabel51.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel51.setText("Edad:");

        ComboMateriasasp.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Calculo Diferencial", "Calculo Integral", "Calculo Multivariado", "Fisica Mecanica", "Electromagnetica", "Programacion Basica", "Programacion Orientada a Objetos" }));

        jLabel22.setBackground(new java.awt.Color(255, 255, 255));
        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Carrera:");

        ComboProfesión.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Ingeniero/a de Sistemas", "Ingeniero/a Industrial", "Ingeniero/a Mecánico/a", "Ingeniero/a Eléctrico/a", "Ingeniero/a  Electrónico/a", "Ingeniero/a Químico/a", " " }));

        jLabel36.setBackground(new java.awt.Color(255, 255, 255));
        jLabel36.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel36.setText("Código de exámen:");

        codexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codexamActionPerformed(evt);
            }
        });

        Verificarexam.setBackground(new java.awt.Color(204, 204, 255));
        Verificarexam.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        Verificarexam.setText("Verificar ");
        Verificarexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VerificarexamActionPerformed(evt);
            }
        });

        jLabel43.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel43.setText("Puntaje:");

        puntajeexam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntajeexamActionPerformed(evt);
            }
        });

        jLabel58.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel58.setText("Fecha citación:");

        fechacitacio.setText("dd-mm-aaaa");
        fechacitacio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fechacitacioActionPerformed(evt);
            }
        });

        BtnGuardarHV2.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnGuardarHV2.setText("Agregar ");
        BtnGuardarHV2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHV2ActionPerformed(evt);
            }
        });

        TxtEdadasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtEdadaspActionPerformed(evt);
            }
        });

        jLabel30.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(39, 39, 39));
        jLabel30.setText("Disponibilidad horaria:");

        BtnGuardarHV3.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        BtnGuardarHV3.setText("Agregar ");
        BtnGuardarHV3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHV3ActionPerformed(evt);
            }
        });

        jLabel40.setFont(new java.awt.Font("Microsoft Tai Le", 1, 18)); // NOI18N
        jLabel40.setForeground(new java.awt.Color(255, 255, 255));
        jLabel40.setText("Escriba los siguientes datos para registrarse:");

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Usuario:");

        TxtUsuasp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuaspActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Contraseña:");

        contra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contraActionPerformed(evt);
            }
        });

        jLabel39.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel39.setText("Confirmar contraseña:");

        verificarcontra.setBackground(new java.awt.Color(204, 204, 255));
        verificarcontra.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        verificarcontra.setText("Comparar");
        verificarcontra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verificarcontraActionPerformed(evt);
            }
        });

        jLabel37.setBackground(new java.awt.Color(255, 255, 255));
        jLabel37.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel37.setText("Lugar de exámen:");

        Combolugarexam.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "...", "Armenia (Quindio)", "Barranquilla (Atlantico)", "Bogota D.C", "Bucaramanga (Santander)", "Cartagena (Bolivar)", "Cucuta (Norte de Santander)", "Pereira (Risaralda)", "Ibague (Tolima)", "Manizales (Caldas)", "Neiva (Huila)", "Santa Marta (Magdalena)", "Tunja (Boyaca)", "Villavicencio (Meta)" }));

        BtnGuardarHV.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        BtnGuardarHV.setText("Guardar ");
        BtnGuardarHV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel23Layout = new javax.swing.GroupLayout(jPanel23);
        jPanel23.setLayout(jPanel23Layout);
        jPanel23Layout.setHorizontalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel27)
                        .addGap(797, 797, 797)
                        .addComponent(jLabel40)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel42)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 896, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jSeparator3)
                            .addGroup(jPanel23Layout.createSequentialGroup()
                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel26, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel44, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel58)
                                            .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(TxtNombreasp, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                    .addComponent(TxtCcasp, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                .addGap(59, 59, 59)
                                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                                        .addComponent(jLabel37, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Combolugarexam, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                                        .addComponent(jLabel43)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(puntajeexam, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                                        .addComponent(jLabel36, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                        .addComponent(codexam, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addComponent(fechacitacio, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(53, 53, 53)
                                                .addComponent(Verificarexam, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGap(156, 156, 156)
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(ComboMateriasasp, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(BtnGuardarHV2, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addGap(107, 107, 107)
                                                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addGap(139, 139, 139)
                                                .addComponent(BtnGuardarHV3, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGap(159, 159, 159)
                                        .addComponent(TxtUsuasp, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(53, 53, 53)
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(4, 4, 4)
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(contra, javax.swing.GroupLayout.DEFAULT_SIZE, 177, Short.MAX_VALUE)
                                            .addComponent(recontra))
                                        .addGap(37, 37, 37)
                                        .addComponent(verificarcontra, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                                        .addComponent(jLabel49, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ComboUbiasp, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(jPanel23Layout.createSequentialGroup()
                                                        .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(ComboProfesión, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel23Layout.createSequentialGroup()
                                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addComponent(jLabel46, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel47, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel51, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                            .addComponent(jLabel48, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                    .addComponent(Txtelasp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(Txtdirasp, javax.swing.GroupLayout.PREFERRED_SIZE, 331, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                    .addComponent(TxtEdadasp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                                            .addGroup(jPanel23Layout.createSequentialGroup()
                                                                .addGap(2, 2, 2)
                                                                .addComponent(TxtCorreoasp, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                                                .addGap(14, 14, 14))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 575, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(76, 76, 76))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                                                .addComponent(BtnGuardarHV, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(48, 48, 48)))
                                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        jPanel23Layout.setVerticalGroup(
            jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel23Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel44)
                    .addComponent(TxtCcasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(codexam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel36))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(TxtNombreasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(puntajeexam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel43))
                    .addComponent(jLabel45, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fechacitacio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Verificarexam))
                    .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel37)
                        .addComponent(Combolugarexam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel58))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(TxtUsuasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(contra, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel40)
                                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(recontra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel39, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(verificarcontra))))
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel42)
                            .addComponent(ComboMateriasasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel30))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnGuardarHV2)
                            .addComponent(BtnGuardarHV3))))
                .addGap(17, 17, 17)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel23Layout.createSequentialGroup()
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel46)
                            .addComponent(Txtdirasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel47)
                            .addComponent(Txtelasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel51)
                            .addComponent(TxtEdadasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel48)
                            .addComponent(TxtCorreoasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel22)
                            .addComponent(ComboProfesión, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel23Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel49)
                            .addComponent(ComboUbiasp, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnGuardarHV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel23Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addContainerGap())))
        );

        BtnIngresar3.setBackground(new java.awt.Color(255, 255, 255));
        BtnIngresar3.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        BtnIngresar3.setText("Salir");
        BtnIngresar3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresar3ActionPerformed(evt);
            }
        });

        BtnGuardarHV1.setBackground(new java.awt.Color(204, 204, 255));
        BtnGuardarHV1.setFont(new java.awt.Font("Microsoft Tai Le", 1, 14)); // NOI18N
        BtnGuardarHV1.setText("Volver a Inicio");
        BtnGuardarHV1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnGuardarHV1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, 931, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BtnGuardarHV1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnIngresar3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnGuardarHV1)
                        .addGap(18, 18, 18)
                        .addComponent(BtnIngresar3)
                        .addGap(16, 16, 16))
                    .addComponent(jPanel23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(539, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnIngresar3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresar3ActionPerformed

        //cierro mi programa
        this.show(false);
        System.exit(0);

        // TODO add your handling code here:
    }//GEN-LAST:event_BtnIngresar3ActionPerformed

    private void BtnGuardarHV1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHV1ActionPerformed
        new Inicio().setVisible(true);  
                this.show(false);
// TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarHV1ActionPerformed

    private void BtnGuardarHVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHVActionPerformed

        //
        try {
            String sFichero = "Tutores.csv";
            File fichero = new File(sFichero);
            if(fichero.exists()){
            }else{
                ltu.crearcvstutor();
            }
            if((usuarioasp!=null)&&(nombre!=null)&&(contrasp!=null)&&(tipo!=null)){

                tel=Txtelasp.getText().toString();
                telasp=Long.parseLong(tel);
                edad=TxtEdadasp.getText().toString();

                edadasp=Long.parseLong(edad);System.out.println("nombre"+nombre);
                System.out.println("tipo"+tipo);
                //nomtut, dirtut, fechaci, lugarci, corrtut, ubitut, proftut, cartera, numt, codexam,
                //puntaje, edadtut, cctut, teltut, usuario, tipo, nombreusuario, contraseña
                ltu.tutor(TxtNombreasp.getText().toString(), Txtdirasp.getText().toString(),
                    fechacitacio.getText().toString(),Combolugarexam.getSelectedItem().toString(),
                    TxtCorreoasp.getText().toString(),ComboUbiasp.getSelectedItem().toString(),
                    ComboProfesión.getSelectedItem().toString(),cartera,numt,codexamen,
                    puntaje,edadasp,ccasp,telasp,usuarioasp, tipo, nombre, contrasp);

                System.out.println("ahi vamos1");

                for (int j = 0; j < ltu.getAs().size(); j++) {
                    System.out.println("array edad"+ltu.getAs().get(j).getEdadTut());

                }

                ltu.crearcvstutor();
                ltu.crearcvsusu();
                JOptionPane.showMessageDialog(null, "Los datos han sido guardados exitosamente",null,JOptionPane.INFORMATION_MESSAGE);

                System.out.println("lleno");

                System.out.println("tamaño"+ltu.getAs().size());

            }else{
                JOptionPane.showMessageDialog(null, "Por favor ingrese su usuario y contraseña para crear su hoja de vida", null,JOptionPane.ERROR_MESSAGE);

            }

        }catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error",null,JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_BtnGuardarHVActionPerformed

    private void verificarcontraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verificarcontraActionPerformed
        try {
            String sFichero = "Personas.csv";
            File fichero = new File(sFichero);
            if(fichero.exists()){

            }else{
                ltu.crearcvsusu();
            }

            if(estasp!=null){

                usuarioasp=TxtUsuasp.getText().toString();
                //  System.out.println("usuario"+usuarioasp);

                //  System.out.println("nombre"+nombre);
                contrasp= contra.getText().toString();
                //   System.out.println("contraseña"+contrasp);

                for (int i = 0; i < ltu.getPer().size(); i++) {

                    if((usuarioasp.equals(ltu.getPer().get(i).getPersona()))&&(contrasp.equals(ltu.getPer().get(i).getContraseña()))){
                        JOptionPane.showMessageDialog(null, "Error, el usuario y la contraseña ya existen",null,JOptionPane.ERROR_MESSAGE);
                        break;

                    }
                }
                if(contra.getText().toString().equals(recontra.getText().toString())){

                    ltu.persona(usuarioasp, tipo, nombre, contrasp);
                    JOptionPane.showMessageDialog(null, "Las contraseñas son iguales",null,JOptionPane.INFORMATION_MESSAGE);

                }else{
                    JOptionPane.showMessageDialog(null, "Error, las contraseñas no coinciden",null,JOptionPane.ERROR_MESSAGE);
                }
            }else{
                System.out.println("nopi");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Error",null,JOptionPane.ERROR_MESSAGE);

        }
        // TODO add your handling code here:
    }//GEN-LAST:event_verificarcontraActionPerformed

    private void contraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_contraActionPerformed

    private void TxtUsuaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuaspActionPerformed

    private void BtnGuardarHV3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHV3ActionPerformed

        System.out.println("ccasp"+ccasp);
        HorarioTutor ht=new HorarioTutor();
        ht.setScc(ccasp);
        ht.setVisible(true);

    }//GEN-LAST:event_BtnGuardarHV3ActionPerformed

    private void TxtEdadaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtEdadaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtEdadaspActionPerformed

    private void BtnGuardarHV2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnGuardarHV2ActionPerformed

        try {
            if(ComboMateriasasp.getSelectedItem().toString().equals("...")){
                JOptionPane.showMessageDialog(null, "Ingrese una materia",null,JOptionPane.ERROR_MESSAGE);
            }
            ltu.crearma(ccasp, ComboMateriasasp.getSelectedItem().toString());
            ltu.crearcvsma();
            JOptionPane.showMessageDialog(null, "Materia agregada",null,JOptionPane.INFORMATION_MESSAGE);

        } catch (Exception e) {
        }
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnGuardarHV2ActionPerformed

    private void fechacitacioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fechacitacioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fechacitacioActionPerformed

    private void puntajeexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntajeexamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_puntajeexamActionPerformed

    private void VerificarexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VerificarexamActionPerformed
        try {
            cc=TxtCcasp.getText().toString();
            ccasp= Long.parseLong(cc);
            nombre=TxtNombreasp.getText().toString();
            String fechacita=fechacitacio.getText().toString();
            String cod=codexam.getText();
            codexamen= Long.parseLong(cod);
            String punt=puntajeexam.getText();
            puntaje= Long.parseLong(punt);
            String lugare=Combolugarexam.getSelectedItem().toString();

            for (int i = 0; i <ltu.getCa().size(); i++) {

                if(((ccasp==ltu.getCa().get(i).getCcTut())&&(codexamen==ltu.getCa().get(i).getCodExam()))&&(puntaje==ltu.getCa().get(i).getPuntaje())){

                    if (ltu.getCa().get(i).getPuntaje()>=80) {
                        JOptionPane.showMessageDialog(null, "Es apto para ser tutor",null,JOptionPane.INFORMATION_MESSAGE);
                        estasp="Tutor";
                    }
                    break;
                }else if(i+1==ltu.getCa().size()){
                    JOptionPane.showMessageDialog(null, "No es apto para ser tutor",null,JOptionPane.ERROR_MESSAGE);
                }
            }
        }catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Error",null,JOptionPane.ERROR_MESSAGE);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_VerificarexamActionPerformed

    private void codexamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codexamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codexamActionPerformed

    private void TxtCorreoaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCorreoaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCorreoaspActionPerformed

    private void TxtelaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtelaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtelaspActionPerformed

    private void TxtdiraspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtdiraspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtdiraspActionPerformed

    private void TxtNombreaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNombreaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNombreaspActionPerformed

    private void TxtCcaspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtCcaspActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtCcaspActionPerformed

    public JTextField getTxtCcasp() {
        return TxtCcasp;
    }

    
    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnGuardarHV;
    private javax.swing.JButton BtnGuardarHV1;
    private javax.swing.JButton BtnGuardarHV2;
    private javax.swing.JButton BtnGuardarHV3;
    private javax.swing.JButton BtnIngresar3;
    private javax.swing.JComboBox ComboMateriasasp;
    private javax.swing.JComboBox ComboProfesión;
    private javax.swing.JComboBox ComboUbiasp;
    private javax.swing.JComboBox Combolugarexam;
    public static javax.swing.JTextField TxtCcasp;
    private javax.swing.JTextField TxtCorreoasp;
    private javax.swing.JTextField TxtEdadasp;
    private javax.swing.JTextField TxtNombreasp;
    private javax.swing.JTextField TxtUsuasp;
    private javax.swing.JTextField Txtdirasp;
    private javax.swing.JTextField Txtelasp;
    private javax.swing.JButton Verificarexam;
    private javax.swing.JTextField codexam;
    private javax.swing.JPasswordField contra;
    private javax.swing.JTextField fechacitacio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel58;
    private javax.swing.JPanel jPanel23;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTextField puntajeexam;
    private javax.swing.JPasswordField recontra;
    private javax.swing.JButton verificarcontra;
    // End of variables declaration//GEN-END:variables
}
